-- 코드를 입력하세요
SELECT M.MEMBER_NAME,N.REVIEW_TEXT, DATE_FORMAT(N.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW N JOIN MEMBER_PROFILE M
ON M.MEMBER_ID = N.MEMBER_ID
WHERE M.MEMBER_ID = (
    SELECT MEMBER_ID FROM(
    SELECT MEMBER_ID,COUNT(*) AS COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT DESC LIMIT 1
    ) K
)
ORDER BY REVIEW_DATE, REVIEW_TEXT



